title: POLS 8810 (Spring 2023)
logo: /assets/img/logo.png
description: Ozlem uses this website to share any information about POLS 8810 (Spring 2023). Image created using DALL-E.
show_downloads: false
google_analytics: G-VNCMS8545D
theme: jekyll-theme-minimal
